
monolith_module.gallery.admin:
    path: /
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::indexAction

monolith_module.gallery.admin_gallery:
    path: /gallery_{id}/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::galleryAction

monolith_module.gallery.admin_gallery_edit:
    path: /gallery_{id}/edit/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::galleryEditAction

monolith_module.gallery.admin_album:
    path: /gallery_{gallery_id}/album_{id}/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::albumAction

monolith_module.gallery.admin_album_edit:
    path: /gallery_{gallery_id}/album_{id}/edit/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::albumEditAction

monolith_module.gallery.admin_photo_make_cover:
    path: /gallery_{gallery_id}/album_{album_id}/photo_{id}/make_cover/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::photoAction
        set_as_cover: true

monolith_module.gallery.admin_photo:
    path: /gallery_{gallery_id}/album_{album_id}/photo_{id}/
    defaults:
        _controller: Monolith\Module\Gallery\Controller\AdminGalleryController::photoAction
