framework:
    translator: { fallbacks: [ "en" ] }
    secret: '%env(APP_SECRET)%'
    trusted_hosts: ~
    #default_locale: en
    csrf_protection: true
    http_method_override: true
    esi: true
    fragments: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
#    default_locale: 'en'
#    translator:
#        fallbacks: ['en']
    php_errors:
        log: true
    ide: 'phpstorm://open?url=file://%%f&line=%%l'
    validation:
        email_validation_mode: 'html5'
        enable_annotations: true
