# @todo переместить в CMSBundle
parameters:
    admin_path: admin
    user_path: user
    mailer_user: test@mail.com
    user_class: App\Entity\User
    cms_prod_url: ~
    uploads_dir: uploads
    liip_theme.filesystem_loader.class: Monolith\CMSBundle\Twig\Loader\FilesystemLoader
    sonata.intl.timezone_detector.chain.class: Monolith\CMSBundle\Timezone\SonataChainTimezoneDetector
    router.class: Monolith\CMSBundle\Router\NodeRouter

