twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
#    strict_variables: false # @todo пока только так, потому что требуется для mopa/bootstrap-bundle
