
monolith_module.texter.admin:
    path: /
    defaults:
        _controller: Monolith\Module\Texter\Controller\AdminController::indexAction

monolith_module.texter.admin.history:
    path: /{id}/history/
    defaults:
        _controller: Monolith\Module\Texter\Controller\AdminController::historyAction
    requirements:
        id: \d+

monolith_module.texter.admin.history_view:
    path: /{id}/history/view/
    defaults:
        _controller: Monolith\Module\Texter\Controller\AdminController::historyViewAction
    requirements:
        id: \d+

monolith_module.texter.admin.rollback:
    path: /rollback/{id}/
    defaults:
        _controller: Monolith\Module\Texter\Controller\AdminController::rollbackAction
    requirements:
        id: \d+

monolith_module.texter.admin.edit:
    path: /{id}/
    defaults:
        _controller: Monolith\Module\Texter\Controller\AdminController::itemAction
    requirements:
        id: \d+
