services:
    Monolith\Module\Texter\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    monolith_module.texter:
        class: Monolith\Module\Texter\Service\TexterService
        public: true
        arguments: [ '@cms.cache', '@doctrine.orm.entity_manager' ]
