#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# easy_admin должны быть в конце списка
#easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
#    prefix: /admin/easy/
#    type: annotation
