
#index:
#    path: /
#    defaults:
#        _controller: CMSBundle:Admin:dashboard

#logout:
#    path: /logout
#    defaults:
#        _controller: FOSUserBundle:Security:logout

#system:
#    resource: 'routing_admin_system.yml'
#    prefix: /system/

node: # @deprecated
    path: /node/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeAction
    requirements:
        id: \d+

node_w_slug: # @deprecated
    path: /node/{id}/{slug}
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeAction
    requirements:
        id: \d+
        slug: '.+'

#module_full_path:
#    path: /{name}/
#    defaults:
#        _controller: CMSBundle:Admin:module


# @todo
#help:
#    path: /help/
#    defaults:
#        _controller: CMSBundle:Admin:notFound


# ... other
#404:
#    path: /{slug}
#    defaults:
#        _controller: CMSBundle:Admin:notFound
#        slug: ''
#    requirements:
#        slug: '.+'
