system:
    path: /
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminController::notFoundAction

files:
    path: /files/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminController::elfinderAction

# Modules
module:
    path: /modules/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminModuleController::enabledAction

module_disabled:
    path: /modules/disabled/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminModuleController::disabledAction

module_all:
    path: /modules/all/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminModuleController::indexAction

module_install_updatedb:
    path: /modules/install/updatedb
    methods: 'POST'
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminModuleController::moduleInstallUpdateDbAction

module_install:
    path: /modules/install/{filename}
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminModuleController::installAction
        filename: ''

# languages
language:
    path: /language/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminLanguageController::indexAction

language_create:
    path: /language/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminLanguageController::createAction

language_edit:
    path: /language/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminLanguageController::editAction
    requirements:
        id: \d+

# development
development:
    path: /development/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDevelopmentController::indexAction

development_sync:
    path: /development/sync/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDevelopmentController::syncAction

development_db:
    path: /development/db/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDevelopmentController::databaseAction

# sites
site:
    path: /site/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminSiteController::indexAction

site_create:
    path: /site/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminSiteController::createAction

site_edit:
    path: /site/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminSiteController::editAction
    requirements:
        id: \d+

# domains
domains:
    path: /site/domains/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDomainController::indexAction

domain_create:
    path: /domain_create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDomainController::createAction

domain_edit:
    path: /domain/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDomainController::editAction
    requirements:
        id: \d+

domain_create_alias:
    path: /domain_create_alias/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminDomainController::createAliasAction
    requirements:
        id: \d+

# reports
reports:
    path: /reports/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminController::reports

# Backup
backup_download:
    path: /backup/{filename}
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminController::backupDownload
        filename: '.+'

backup:
    path: /backup/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminController::backupIndex

# Structure
structure_index:
    path: /structure/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::structureAction

structure:
    path: /structure/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::structureAction

megastructure:
    path: /megastructure/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::megastructureAction

structure_trash:
    path: /structure/trash/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::trashAction

structure_trash_restore_node:
    path: /structure/trash/restore_node/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::trashRestoreNodeAction

structure_trash_purge_node:
    path: /structure/trash/purge_node/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::trashPurgeNodeAction

structure_trash_restore_folder:
    path: /structure/trash/restore_folder/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::trashRestoreFolderAction

structure_trash_purge_folder:
    path: /structure/trash/purge_folder/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::trashPurgeFolderAction

# Region
structure_region:
    path: /structure/region/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::regionIndexAction

structure_region_edit:
    path: /structure/region/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::regionEditAction
    requirements:
        id: \d+

# Folder
structure_folder_create:
    path: /structure/folder/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::folderCreateAction
#        parent: 1

structure_folder_create_in_folder:
    path: /structure/folder/create/{parent}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::folderCreateAction
    requirements:
        parent: \d+

structure_folder:
    path: /structure/folder/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::folderEditAction
    requirements:
        id: \d+

# Node
structure_node_create:
    path: /structure/node/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeCreateAction

structure_node_create_in_folder:
    path: /structure/node/create/{folder_pid}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeCreateAction

#structure_node_all:
#    path: /structure/node/
#    defaults:
#        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeAction

structure_node_properties:
    path: /structure/node/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeEditAction
    requirements:
        id: \d+

structure_node_setup_controller:
    path: /structure/node/{id}/setup_controller/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminStructureController::nodeSetupControllerAction
    requirements:
        id: \d+

# Appearance
appearance:
    path: /appearance/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::indexAction

appearance_template:
    path: /appearance/{name}.twig/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::templateEditAction

appearance_template_history:
    path: /appearance/{name}.twig/history/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::templateHistoryAction

appearance_style_history:
    path: /appearance/{name}/history/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::styleHistoryAction

appearance_history_code:
    path: /appearance/history/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::historyCodeAction

appearance_history_rollback:
    path: /appearance/history/rollback/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::historyRollbackAction

appearance_style:
    path: /appearance/{name}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminAppearanceController::styleEditAction

# Users
user:
    path: /user/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::indexAction

user_create:
    path: /user/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::createAction

user_groups:
    path: /user/groups/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::groupsAction

user_group_edit:
    path: /user/group/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::groupEditAction
    requirements:
        id: \d+

user_group_create:
    path: /user/group/create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::groupCreateAction
    requirements:
        id: \d+

user_edit:
    path: /user/{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminUserController::editAction

# Configuration

config_media:
    path: /config/media/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminMediaLibraryController::indexAction

config_media_create_storage:
    path: /config/media/storage_create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminMediaLibraryController::createStorageAction

config_media_edit_storage:
    path: /config/media/storage_{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminMediaLibraryController::editStorageAction
    requirements:
        id: \d+

config_media_create_collection:
    path: /config/media/collection_create/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminMediaLibraryController::createCollectionAction

config_media_edit_collection:
    path: /config/media/collection_{id}/
    defaults:
        _controller: Monolith\CMSBundle\Controller\AdminMediaLibraryController::editCollectionAction
    requirements:
        id: \d+
