cms.smart_media:
    resource: '@SmartMediaBundle/Resources/config/routing.yml'
    prefix: /_media/

cms_admin.site_switch_selected:
    path: /__cms_site_switch_selected/
    methods: POST
    defaults:
        _controller: Monolith\CMSBundle\Controller\CmsController::switchSelectedSiteAction

cms_api:
    resource: routing_api.yml
    prefix: /%api_path%/

cms_admin:
    resource: routing_admin.yml
    name_prefix: 'cms_admin.'
    prefix: /%admin_path%/

admin_settings:
    resource: '@SmartSettingsBundle/Resources/config/routing.yml'
    prefix: /%admin_path%/system/config/

# @todo   Подлючение маршрутов модулей в админку.
module_routes:
    resource: .
    type: module_admin
    prefix: /%admin_path%/

#elfinder:
#    resource: '@FMElfinderBundle/Resources/config/routing.yml'

controllers:
    resource: '../../../Controller/'
    type: annotation

# Эти маршруты нужны для генерации ссылок к модулям с учетом пути, куда они подключены.
#cms_modules:
#    resource: .
#    type: modules_enabled

cms_modules:
    resource: .
    type: modules_annotation

fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'
    prefix: /%user_path%

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /%user_path%

fos_user_register:
    resource: '@FOSUserBundle/Resources/config/routing/registration.xml'
    prefix: /%user_path%/register

fos_user_resetting:
    resource: '@CMSBundle/Resources/config/routing/fosuser_resetting.xml'
    prefix: /%user_path%/resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /%user_path%
