
cms_api.syslog:
    path: /syslog/
    defaults:
        _controller: Monolith\CMSBundle\Controller\ApiController::syslogAction

cms_api.get_database_dump:
    path: /get_db_dump/
    defaults:
        _controller: Monolith\CMSBundle\Controller\ApiController::getDatabaseDumpAction

cms_api:
    path: /
    defaults:
        _controller: CMSBundle:FrontEnd:apiNotFound

cms_api.node_index:
    path: /{node_id}/
    defaults:
        _controller: CMSBundle:FrontEnd:api
        slug: ''
    requirements:
        node_id: \d+

cms_api.node:
    path: /{node_id}/{slug}
    defaults:
        _controller: CMSBundle:FrontEnd:api
        slug: ''
    requirements:
        slug: '.+'
        node_id: \d+

cms_api.not_found:
    path: /{slug}
    defaults:
        _controller: CMSBundle:FrontEnd:apiNotFound
        slug: ''
    requirements:
        slug: '.+'
