system:
    path: /
    defaults:
        _controller: CMSBundle:Admin:notFound

files:
    path: /files/
    defaults:
        _controller: CMSBundle:Admin:elfinder

# Modules
module:
    path: /module/
    defaults:
        _controller: CMSBundle:AdminModule:enabled

module_disabled:
    path: /module/disabled/
    defaults:
        _controller: CMSBundle:AdminModule:disabled

module_all:
    path: /module/all/
    defaults:
        _controller: CMSBundle:AdminModule:index

module_install_updatedb:
    path: /module/install/updatedb
    methods: 'POST'
    defaults:
        _controller: CMSBundle:AdminModule:moduleInstallUpdateDb

module_install:
    path: /module/install/{filename}
    defaults:
        _controller: CMSBundle:AdminModule:install
        filename: ''

# languages
language:
    path: /language/
    defaults:
        _controller: CMSBundle:AdminLanguage:index

language_create:
    path: /language/create/
    defaults:
        _controller: CMSBundle:AdminLanguage:create

language_edit:
    path: /language/{id}/
    defaults:
        _controller: CMSBundle:AdminLanguage:edit
    requirements:
        id: \d+

# development
development:
    path: /development/
    defaults:
        _controller: CMSBundle:AdminDevelopment:index

development_sync:
    path: /development/sync/
    defaults:
        _controller: CMSBundle:AdminDevelopment:sync

development_db:
    path: /development/db/
    defaults:
        _controller: CMSBundle:AdminDevelopment:database

# sites
site:
    path: /site/
    defaults:
        _controller: CMSBundle:AdminSite:index

site_create:
    path: /site/create/
    defaults:
        _controller: CMSBundle:AdminSite:create

site_edit:
    path: /site/{id}/
    defaults:
        _controller: CMSBundle:AdminSite:edit
    requirements:
        id: \d+

# domains
domains:
    path: /site/domains/
    defaults:
        _controller: CMSBundle:AdminDomain:index

domain_create:
    path: /domain_create/
    defaults:
        _controller: CMSBundle:AdminDomain:create

domain_edit:
    path: /domain/{id}/
    defaults:
        _controller: CMSBundle:AdminDomain:edit
    requirements:
        id: \d+

domain_create_alias:
    path: /domain_create_alias/{id}/
    defaults:
        _controller: CMSBundle:AdminDomain:createAlias
    requirements:
        id: \d+

# reports
reports:
    path: /reports/
    defaults:
        _controller: CMSBundle:Admin:reports

# Backup
backup_download:
    path: /backup/{filename}
    defaults:
        _controller: CMSBundle:Admin:backupDownload
        filename: '.+'

backup:
    path: /backup/
    defaults:
        _controller: CMSBundle:Admin:backupIndex

# Structure
structure_index:
    path: /structure/
    defaults:
        _controller: CMSBundle:AdminStructure:structure

structure:
    path: /structure/
    defaults:
        _controller: CMSBundle:AdminStructure:structure

megastructure:
    path: /megastructure/
    defaults:
        _controller: CMSBundle:AdminStructure:megastructure

structure_trash:
    path: /structure/trash/
    defaults:
        _controller: CMSBundle:AdminStructure:trash

structure_trash_restore_node:
    path: /structure/trash/restore_node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashRestoreNode

structure_trash_purge_node:
    path: /structure/trash/purge_node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashPurgeNode

structure_trash_restore_folder:
    path: /structure/trash/restore_folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashRestoreFolder

structure_trash_purge_folder:
    path: /structure/trash/purge_folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:trashPurgeFolder

# Region
structure_region:
    path: /structure/region/
    defaults:
        _controller: CMSBundle:AdminStructure:regionIndex

structure_region_edit:
    path: /structure/region/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:regionEdit
    requirements:
        id: \d+

# Folder
structure_folder_create:
    path: /structure/folder/create/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
#        parent: 1

structure_folder_create_in_folder:
    path: /structure/folder/create/{parent}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
    requirements:
        parent: \d+

structure_folder:
    path: /structure/folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderEdit
    requirements:
        id: \d+

# Node
structure_node_create:
    path: /structure/node/create/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

structure_node_create_in_folder:
    path: /structure/node/create/{folder_pid}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

#structure_node_all:
#    path: /structure/node/
#    defaults:
#        _controller: CMSBundle:AdminStructure:node

structure_node_properties:
    path: /structure/node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeEdit
    requirements:
        id: \d+

structure_node_setup_controller:
    path: /structure/node/{id}/setup_controller/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeSetupController
    requirements:
        id: \d+

# Appearance
appearance:
    path: /appearance/
    defaults:
        _controller: CMSBundle:AdminAppearance:index

appearance_template:
    path: /appearance/{name}.twig/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateEdit

appearance_template_history:
    path: /appearance/{name}.twig/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateHistory

appearance_style_history:
    path: /appearance/{name}/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleHistory

appearance_history_code:
    path: /appearance/history/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyCode

appearance_history_rollback:
    path: /appearance/history/rollback/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyRollback

appearance_style:
    path: /appearance/{name}/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleEdit

# Users
user:
    path: /user/
    defaults:
        _controller: CMSBundle:AdminUser:index

user_create:
    path: /user/create/
    defaults:
        _controller: CMSBundle:AdminUser:create

user_groups:
    path: /user/groups/
    defaults:
        _controller: CMSBundle:AdminUser:groups

user_group_edit:
    path: /user/group/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:groupEdit
    requirements:
        id: \d+

user_group_create:
    path: /user/group/create/
    defaults:
        _controller: CMSBundle:AdminUser:groupCreate
    requirements:
        id: \d+

user_edit:
    path: /user/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:edit

# Configuration

config_media:
    path: /config/media/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:index

config_media_create_storage:
    path: /config/media/storage_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createStorage

config_media_edit_storage:
    path: /config/media/storage_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editStorage
    requirements:
        id: \d+

config_media_create_collection:
    path: /config/media/collection_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createCollection

config_media_edit_collection:
    path: /config/media/collection_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editCollection
    requirements:
        id: \d+
