theme_index:
    path: /
    defaults:
        _controller: CMSBundle:AdminTheme:index

theme_show:
    path: /{name}/
    defaults:
        _controller: CMSBundle:AdminTheme:theme

theme_file_edit:
    path: /{theme}/{dir}:{relativePathname}
    defaults:
        _controller: CMSBundle:AdminTheme:fileEdit
    requirements:
        relativePathname: '.+'

theme_get_screenshot:
    path: /get_screenshot/{theme}/{filename}
    defaults:
        _controller: CMSBundle:AdminTheme:getScreenshot
