security:
    always_authenticate_before_granting: true
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
        #App\Entity\User:
            algorithm: 'argon2i' # 'auto' # 'sodium'
            cost:      30

    providers:
        #in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username
#        database_users:
#            entity: { class: App\Entity\User, property: username }
#        backend_users:
#            memory:
#                users:
#                    test: { password: '$argon2i$v=19$m=1024,t=2,p=2$dUJPcHR2cjhlMzVidUlhRg$+CFhcNgXNnHylSCirj9MjEDO4ry0+3pSv3L1FGWNfms', roles: ['ROLE_ADMIN'] }
#        all_users:
#            chain:
#                providers: ['database_users', 'backend_users']

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ADMIN_CONFIG, ROLE_ALLOWED_TO_SWITCH, ROLE_FILEMANAGER ]
        ROLE_ROOT:        [ ROLE_SUPER_ADMIN ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            context: monolith_cms
            pattern: ^/%admin_path%
            form_login:
                provider: fos_userbundle
                check_path: /%admin_path%/login_check
                login_path: /%admin_path%/
                default_target_path: /%admin_path%/
            logout:
                path: /%admin_path%/logout
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~
        main:
            anonymous: ~
            context: monolith_cms
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_provider: form.csrf_provider # @deprecated in 3.x
                check_path: /%user_path%/login_check
                login_path: /%user_path%/
                default_target_path: /%user_path%/
            logout:
                path: /%user_path%/logout
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: REMEMBER_ME
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
#    access_control:
#        - { path: ^/_assistant/, roles: ROLE_ADMIN }
#        - { path: ^/%admin_path%/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%admin_path%/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%admin_path%/system/config/, role: ROLE_ADMIN_CONFIG }
#        - { path: ^/%admin_path%, roles: ROLE_ADMIN }
#        - { path: ^/efconnect, role: ROLE_FILEMANAGER }
#        - { path: ^/elfinder, role: ROLE_FILEMANAGER }
#        - { path: ^/%user_path%/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%user_path%, roles: ROLE_USER }
