smart_rich_editor:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: 'wysiwyg'
    language: "%locale%"
    theme:
        advanced:
            file_browser_callback : 'elFinderBrowser'
            theme: 'advanced'
            plugins: 'autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist'
            theme_advanced_buttons1: 'save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect'
            theme_advanced_buttons2: 'cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor'
            theme_advanced_buttons3: 'tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen'
            theme_advanced_toolbar_location: 'top'
            theme_advanced_toolbar_align: 'left'
            theme_advanced_statusbar_location: 'bottom'
            theme_advanced_resizing: true
            theme_advanced_resizing_use_cookie: true
            theme_advanced_resize_horizontal: false
            force_br_newlines : false
            forced_root_block : ''
            convert_urls : false
            relative_urls: false
            width: '100%'
            height: 380
            content_css: 'asset[bundles/felib/tinymce/content.css]'
        simple:
            theme: 'simple'
            force_br_newlines : false
            forced_root_block : ''
            convert_urls : false
            relative_urls: false
            width: '100%'
            height: 180
            content_css: 'asset[bundles/felib/tinymce/content.css]'
