services:
    # CMS
    cms.context:
        class: Monolith\CMSBundle\Manager\ContextManager
        public: true
        arguments: [ '@service_container', '@fos_user.user_manager' ]

    # Twig
    cms.twig.extension:
        class: Monolith\CMSBundle\Twig\CmsExtension
        arguments: [ '@service_container' ]
        tags:
            - { name: twig.extension }
