# Short format
option1: value 1

# Full specs
option2:
    type: TextType # CheckboxType, ChoiceType, CheckboxType etc...
    hidden: true # Скрывать в админке
    value: |
        Многострочный
        Текст.
    title: Если указан заголовок, то будет отображаться вместо имени.
    description: Подробное описание настройки
    validation:
        - NotBlank: ~
        - Range:
            min: 120
            max: 180
    choices:
        ru: Россия
        de: Германия


    # @todo
    group: main # @todo Додумать группы
    update_callback: \My\Setting\Callback::option2 # Вызов стататического метода либо сервиса при обновлении параметра.
