smart_core_settings:
    path: /
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::indexAction

smart_core_settings_personal:
    path: /personal/
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::indexAction
        personal: true

smart_core_setting_edit:
    path: /{bundle}:{name}/
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::editAction

smart_core_setting_edit_personal:
    path: /personal/{bundle}:{name}/
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::editAction
        personal: true

smart_core_setting_history:
    path: /{bundle}:{name}/history/
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::historyAction

smart_core_setting_history_rollback:
    path: /rollback/{id}/
    defaults:
        _controller: SmartCore\Bundle\SettingsBundle\Controller\SettingsController::rollbackAction
    requirements:
        id: \d+
