parameters:
    smart_media.local.provider: SmartCore\Bundle\MediaBundle\Provider\LocalProvider

services:
    smart_media:
        class: SmartCore\Bundle\MediaBundle\Service\MediaCloudService
        arguments: [ '@service_container' ]
        public: true

    smart_media.generator:
        public: true
        class: SmartCore\Bundle\MediaBundle\Service\GeneratorService

    smart_media.twig.extension:
        class: SmartCore\Bundle\MediaBundle\Twig\MediaExtension
        arguments: [ '@smart_media' ]
        tags:
            - { name: twig.extension }
